### ISSUE TITLE
Should ./bin be added to gitignore?

### ISSUE THREAD

**Issue by bbimber** [LabKey/testAutomation#979]
My understanding is that we're supposed to download the browser drivers into ./testAutomation/bin. If true, should this location be added to .gitignore?

**Comment by labkey-tchad** [comment]
There isn't a particular place we indicate to install them anymore. WebDriver can find them on your system `PATH` or in locations specified in your test properties (`webdriver.gecko.driver`/`webdriver.chrome.driver`).
We recommend just installing a single copy that can be shared by multiple enlistments.
https://www.labkey.org/Documentation/wiki-page.view?name=runningTests
